version: 2.1

orbs:
  aws-cli: circleci/aws-cli

jobs:
  test-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout

      - aws-cli/install

      - aws-cli/configure:
          profile-name: r0se

workflows:
  version: 2
  test-orbs:
    jobs:
      - test-aws-cli:
          context: aws