version: 2
jobs:
  build:
    machine: true
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup custom Docker image
          command: |
            docker pull ruby
            mkdir /abc
            touch /abc/test
            docker run -v /abc:/xyz ruby ls -la /xyz
            abort