version: 2
jobs:
  jest-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: jest-results

  eslint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: eslint-results

  flow-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: flow-results

  stylelint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: stylelint-results

  everything-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: all-test-results

  everything-results-no-flow:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: all-test-results-except-flow

workflows:
  version: 2
  test-results:
    jobs:
      - jest-results
      - eslint-results
      - flow-results
      - stylelint-results

      - everything-results:
          requires:
            - jest-results
            - eslint-results
            - flow-results
            - stylelint-results

      - everything-results-no-flow:
          requires:
            - jest-results
            - eslint-results
            - flow-results
            - stylelint-results