version: 2.1

orbs:
  build-tools: circleci/build-tools@volatile

jobs:
  build:
    docker:
      - image: openjdk12:x86_64-ubuntu-jdk-12.0.1_12
    steps:

      - checkout

      - build-tools/env-info

      - build-tools/install-ci-tools

      - store_artifacts:
          path: ~/.ccidiag/env-info
