version: 2
jobs:
  machine:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run: docker build -t iynere/caching-test:direct .
      - run: bash scripts/build.sh


  remote-docker:
    docker:
      - image: circleci/ruby

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -t iynere/caching-test:direct .
      - run: bash scripts/build.sh


workflows:
  version: 2
  machine-remote-docker:
    jobs:
      - machine
      - remote-docker