version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "build"

  test:
    machine: true
    steps:
      - checkout
      - run: echo "test"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master

  test:
    jobs:
      - test:
          filters:
            tags:
              only: test
              ignore: //