version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true

      - run: docker --version