workflows:
  version: 2
  test_machine_images:
    jobs:
      - default
      - latest
      - edge
      - 03-01
      - 07-01
      - 08-01
      - 09-01

version: 2
jobs:
  
  default:
    machine: true
    
  steps:
    - run: |
          docker version
          docker-compose version
      - checkout
    
  latest:
    machine:
      image: circleci/classic:latest
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout
      
  edge:
    machine:
      image: circleci/classic:edge
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout
      
  03-01:
    machine:
      image: circleci/classic:201703-01
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout
      
  07-01:
    machine:
      image: circleci/classic:201707-01
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout
      
  08-01:
    machine:
      image: circleci/classic:201708-01
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout
      
  09-01:
    machine:
      image: circleci/classic:201709-01
    shell: bash --login -eo pipefail
        
    steps:
      - run: |
          docker version
          docker-compose version
      - checkout