version: 2.1

executors:
  test:
    parameters:
      extras:
        type: boolean
        default: false
        description: >
          Load other images into this executor

    resource_class: small
    docker:
      - image: cibuilds/base
      - when:
          condition: <<parameters.extras>>
          steps:
            - image: circleci/postgres

jobs:
  build:
    executor: test
    steps:
      - checkout

workflows:
  test:
    jobs:
      - build