version: 2
jobs:
  build:
    docker:
      - image: iynere/bats-tests:jessie

    steps:
      - checkout

      - run:
          name: show regular bats output
          command: bats scripts/tests.bats

      - run: |
          bats scripts/tests.bats | perl scripts/tap-to-junit.sh > results.xml && \
          mkdir -p test_results/bats && \
          mv results.xml test_results/bats

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results