version: 2
jobs:
  
  build:
    machine: true
    steps:
      - checkout
      
      - run: docker info >/dev/null 2>&1 || service docker start
      - run: redis-cli ping >/dev/null 2>&1 || service redis-server start
      - run: service mongodb status || service mongodb start