version: 2
jobs:
  jest-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: jest-results

  eslint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: eslint-results

  flow-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: flow-results

  stylelint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: stylelint-results

workflows:
  version: 2
  test-results:
    jobs:
      - jest-results
      - eslint-results
      - flow-results
      - stylelint-results