version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile


steps-test: &steps-test
  run: |
    echo "hello"
    echo "another line"
    echo "line 3"
    echo "etc"


jobs:
  build:
    machine: true
    steps:
      - run:
          name: step 0
          command: |
            cd $CIRCLE_INTERNAL_SCRATCH && ls
            cat $CIRCLE_INTERNAL_CONFIG
            cd /tmp && ls
            cd $XDG_RUNTIME_DIR && ls
      - run:
          name: step 1
          command: |
            cd $CIRCLE_INTERNAL_SCRATCH && ls
            cat $CIRCLE_INTERNAL_CONFIG
            cd /tmp && ls
            cd $XDG_RUNTIME_DIR && ls

      - run: |
          printenv
          circleci step halt
      - *steps-test
