version: 2
jobs:
  build:
    machine: true
    
    steps:
      - checkout
      - run:
          name: mac address
          command: |
            sudo ifconfig eth0 down
            sudo ifconfig eth0 hw ether 00:80:48:BA:d1:30
            sudo ifconfig eth0 up