version: 2
jobs:
  build:
    machine: true
    shell: bash --login -eo pipefail
        
    steps:
      - checkout
      
      - run: |
          echo | sudo tee /etc/apt/sources.list.d/mysql.list
          sudo sed -i'bak' '17,18s/^/#/g' /etc/apt/sources.list
      
      - run: |
          nvm i 6.11.3
          nvm alias default 6.11.3
      
      - run: echo 'export PATH=/opt/circleci/.rvm/gems/ruby-2.3.1/bin:$PATH:' >> $BASH_ENV
      
      - run: |
          rvm install 2.3.4
          echo 'export PATH=/opt/circleci/.rvm/gems/ruby-2.3.4/bin:/opt/circleci/.rvm/gems/ruby-2.3.4@global/bin:/opt/circleci/.rvm/rubies/ruby-2.3.4/bin:$PATH:' >> $BASH_ENV
          
      - run: |
          node --version
          ruby --version