version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "af:0a:93:75:51:75:1f:16:90:d9:97:b1:7a:bb:f0:27"

      - run: |
          git clone git@github.com:CircleCI-Public/circleci-dockerfiles.git
          mkdir test
          touch test/foo
          touch test/bar
          cp -rf ~/project/test/* circleci-dockerfiles
          cd circleci-dockerfiles && git checkout -b test && git add . && git commit -m 'testing' && git push origin test