version: 2.1

orbs:
  windows: sandbox/windows-tools@dev:preview
  cli: circleci/circleci-cli@volatile

jobs:
  build:
    executor:
      name: windows/preview-default
      shell: bash.exe
    steps:

      - checkout

      - cli/install
