version: 2.1

orbs:
  docker-publish: circleci/docker-publish@dev:staging-538454b

jobs:
  build:
    machine: true
    steps:
      - checkout
      - docker-publish/build:
          image: iynere/sandbox

  build-with-args:
    machine: true
    steps:
      - checkout
      - docker-publish/build:
          image: iynere/sandbox
          extra_build_args: --build-arg FOO=bar

workflows:
  docker-publish:
    jobs:
      - build
      - build-with-args
      - docker-publish/publish:
          image: iynere/sandbox
          deploy: false