version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          echo "Files changed: $(git log -1 --format="" --name-only)"

          GIT_LOG=$(git log -1 --format="" --name-only)

          echo "Files changed: " $GIT_LOG