version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
      
    steps:
      
      - checkout
      
      - run: echo "foo" > test
      
      - store_artifacts:
          path: test
      
      - run: jq
          
      - run: |
          curl -u $CIRCLE_TOKEN: --request GET https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts
          