version: 2.1

orbs:
  node: circleci/node@1.1.0
  orb-tools: circleci/orb-tools@8.27.2

jobs:
  build:
    executor: orb-tools/macos
    steps:

      - checkout

      - node/install-yarn

      - run: yarn config set cache-folder ~/.cache/yarn
