version: 2
jobs:
  build:
    machine: true
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:circleci:pull" | jq -r '.token')
          curl -s -H "Authorization: Basic username:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:circleci:pull" | jq --raw-output .token