version: 2.1

orbs:
  docker-publish: circleci/docker-publish@dev:staging-cda848f

jobs:
  build:
    machine: true
    steps:
      - docker-publish/check
      - docker-publish/build

  build-with-args:
    machine: true
    steps:
      - docker-publish/check
      - docker-publish/build:
          extra_build_args: --build-arg FOO=bar

workflows:
  jobs:
    - build
    - build-with-args