version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
      
      - image: iynere/phantom:jessie
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      
    steps:
      
      - checkout
      