version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.13
    steps:
      - checkout
      - run: |
          circleci-agent step halt
          echo "stuff"

      - run: echo "test"