version: 2.1

executors:
  ci-base:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: ci-base
    steps:
      - checkout
      - run: docker version

  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: docker version

workflows:
  build:
    jobs:
      - build
      - test