version: 2
jobs:
  build:
    parallelism: 2
    environment:
      - FOO: "bar"
    docker:
      - image: buildpack-deps:trusty
        environment:
          BAZ: "qux"
        
    steps:
      - checkout
      
      - run: echo $FOO
      - run: echo $BAZ