version: 2

# orbs:
#   compare-url: iynere/compare-url@dev:add-bb-functionality-fa5fa6172db2ae10f3c83b8302c26c08f2166d8e

jobs:
  build:
    machine: true
    steps:

      - checkout

      - run: echo $CIRCLE_COMPARE_URL

      # - compare-url/reconstruct

      # - run: cat CIRCLE_COMPARE_URL.txt

  test:
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: token

      - test