version: 2
jobs:
  build:
    machine: true
    
    steps:
      - checkout
      - run:
          name: Setup custom Docker image
          command: |
            docker pull ruby
            sudo mkdir /abc
            sudo touch /abc/test
            sudo docker run -v /abc:/xyz ruby ls -la /xyz