version: 2.1

executors:
  test:
    parameters:
      images:
        type: steps
        default: []
        description: >
          Other images to load into this executor

    resource_class: small
    docker:
      - image: cibuilds/base
      - steps: <<parameters.images>>

jobs:
  build:
    executor: test
    steps:
      - checkout

workflows:
  test:
    jobs:
      - build