version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    
    # mercurial xvfb \
    # locales sudo openssh-client ca-certificates tar gzip parallel \
    # net-tools netcat unzip zip bzip2
    steps:
      - run:
          name: deps
          command: |
            sudo apt-get update && sudo apt-get install -y \
            git openssh-client
      
      - checkout
      
      - persist_to_workspace:
          root: /root/project
          paths:
            - project
            
  other:
    docker:
      - image: ubuntu:16.04
      
    steps:
      - attach_workspace:
          at: /root
            
workflows:
  version: 2
  build&other:
    jobs:
      - build
      - other:
          requires:
            - build