version: 2.1

jobs:
  build:
    machine: true
    shell: /bin/bash -eol pipefail
    steps:
      - checkout

      - run:
          name: Install goss & dgoss (orbify this later)
          command: |
            # rather than give internet scripts SU rights, we install to local user bin and add to path

            export GOSS_DST=~/bin
            curl -fsSL https://goss.rocks/install | sh
            goss -version
            dgoss -version
