version: 2
jobs:
  build:
    parallelism: 2
    environment:
      - FOO: "bar"
    docker:
      - image: circleci/ruby:2.3.5-node-browsers
        environment:
          BAZ: "qux"
        
    steps:
      - checkout
      
      - run: echo $FOO
      - run: echo $BAZ
      
      - run: node --version