version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1
    steps:
      
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}
            
      - checkout
      
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      
      - setup_remote_docker
      
      - run: docker version
    