version: 2
jobs:
  upstream_job:
    machine: true
    steps:
      - checkout
      - run: echo "blah"

  dependent_job:
    machine: true
    steps:
      - checkout
      - run: echo "this should also only run on master since its upstream job only runs on master"

workflows:
  version: 2
  test:
    jobs:
      - upstream_job:
          filters:
            branches:
              only:
                - master
                - staging
                - production
      - dependent_job:
          filters:
            branches:
              only:
                - dependent-job-shouldn't-run-on-this-branch
          requires:
            - upstream_job
