version: 2
defaults: &defaults
    working_directory: /go/src/github.com/MediaMath/akamai-cloudlet
    docker:
      - image: circleci/golang:1.10.0
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build
          command: echo "stuff"
workflows:
  version: 2
  release-pipeline:
    jobs:
      - build:
          context: org-global