workflows:
  version: 2
  machine_remote:
    jobs:
      - machine
      - remote

version: 2
jobs:
  
  machine:
    machine: true
    steps:
      - checkout
      
  remote:
    docker:
      - image: circleci/node:boron
    steps:
      - checkout
      - setup_remote_docker