version: 2
jobs:
  upstream_job:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "blah"

  dependent_job:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "this should also only run on master since its upstream job only runs on master"

workflows:
  version: 2
  test:
    jobs:
      - upstream_job:
          filters:
            branches:
              only:
                - master
      - dependent_job:
          requires:
            - upstream_job