version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      GOSS_DST: /usr/local/bin
      GOSS_FILES_STRATEGY: cp
      GOSS_FILES_PATH: /home/circleci/project
      GOSS_OPTS: --format junit
      GOSS_SLEEP: 5s
    steps:
      - checkout
      - run: curl -fsSL https://goss.rocks/install | sudo sh
      - run: goss -version
      - run: docker build -t iynere/rust:test rust
      - run: dgoss run iynere/rust:test | tee -a test-results/rust/results.xml
      - store_test_results:
          path: test-results
