version: 2

# orbs:
#   compare-url: iynere/compare-url@dev:add-bb-functionality-fa5fa6172db2ae10f3c83b8302c26c08f2166d8e

jobs:
  build:
    machine: true
    steps:

      - checkout

      - run: echo $CIRCLE_COMPARE_URL

      - run: bash find_last_original_job_commit.sh

      - run: cat CIRCLE_COMPARE_URL.txt