version: 2.1

jobs:
  build:
    machine: true
    shell: /bin/bash -eol pipefail
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Install goss & dgoss (orbify this later)
          command: |
            # rather than give internet scripts SU rights, we install to local user bin and add to path

            mkdir ~/bin
            export GOSS_DST=~/bin
            export PATH=$PATH:~/bin
            curl -fsSL https://goss.rocks/install | sh
            goss -version
