version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: circleci/node
    steps:
      - checkout

      - run: git clone git@github.com:CircleCI-Public/circleci-dockerfiles.git