version: 2.1

job:
  branch:
    machine: true
    steps:
      - checkout
      - run: echo "$CIRCLE_TAG"

  tag:
    machine: true
    steps:
      - checkout
      - run: echo "$CIRCLE_BRANCH"

workflows:
  branch-tag:
    jobs:
      - branch

      - tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
