version: 2.1

orbs:
  build-tools: circleci/build-tools@volatile

jobs:
  build:
    docker:
      - image: openjdk:12-oracle
    steps:

      - checkout

      - build-tools/env-info

      - build-tools/install-ci-tools

      - store_artifacts:
          path: ~/.ccidiag/env-info
