version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: this should come from project env vars
          command: echo "$TEST_ENV_VAR_PRECEDENCE"

      - run:
          name: project env vars vs. config env vars
          command: echo "$TEST_ENV_VAR_PRECEDENCE"
          enviroment:
            TEST_ENV_VAR_PRECEDENCE: config

  test:
    machine: true
    steps:
      - checkout

      - run:
          name: project env vars vs. contexts env vars
          command: echo "$TEST_ENV_VAR_PRECEDENCE"

      - run:
          name: project env vars vs. contexts env vars vs. config env vars
          command: echo "$TEST_ENV_VAR_PRECEDENCE"
          enviroment:
            TEST_ENV_VAR_PRECEDENCE: config


workflows:
  version: 2
  jobs:
    - build

    - test:
        contexts:
          test
        requires:
          - build