version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: echo "hello"

workflows:
  version: 2
  test_git_tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^test/