version: 2
jobs:
  
  build:
    docker:
      - image: circleci/postgres:latest
    steps:
      - checkout
      
      - run:
          name: test1
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ $BRANCH_REGEX ]]; then
              echo "does this work?"
            fi
          environment:
            BRANCH_REGEX: /mast*/
            
      - run:
          name: test2
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ /mast*/ ]]; then
              echo "does this work?"
            fi
      