version: 2
jobs:
  build:
    machine: true
    shell: bash --login -eo pipefail
        
    steps:
      - checkout
      
      - run: |
          sudo apt-get update || true
          sudo apt-get install -y httping jq python-dev qt5-default libqt5webkit5-dev
      
      - run: |
          nvm i 6.11.3
          nvm alias default 6.11.3
          rvm --default use 2.3.4
          
      - run: |
          node --version
          npm --version
          ruby --version