version: 2
jobs:
  build:
    docker:
      - image: iynere/jessie-phantom:1
    environment:
      DISPLAY: :99
        
    steps:
      - checkout
      
      - run: phantomjs --version
      
      - run:
          name: start xvfb
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
          
      - run: phantomjs --version