version: 2
jobs:
  build:
    machine: true
    working_directory: ~/master
      
    steps:
      - checkout
      - run:
          name: install macchanger
          command: |
            sudo apt-get install macchanger
            sudo macchanger eth0 -r