version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:

      - checkout

      - run: sudo rm -rf /var/lib/apt/lists/*

      - run: |
          sudo apt-get update

      - run: |
          sudo apt-get -y install lsb-release
