workflows:
  version: 2
  test_remote_docker:
    jobs:
      - default
      - 3-0
      - 5-0
      - 6-0
      - 6-1
      - 6-2
      - 7-0
      - 9-0

version: 2
jobs:
  
  default:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
    
  3-0:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  5-0:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  6-0:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  6-1:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  6-2:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  7-0:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker
      
  9-0:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - run: |
          docker version
          docker-compose version
      
      - checkout
      
      - setup_remote_docker