version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    
    steps:
      - checkout
      
      - persist_to_workspace:
          root: /root/project
          paths:
            - project
            
  other:
    docker:
      - image: ubuntu:16.04
      
    steps:
      - attach_workspace:
          at: /root
            
workflows:
  version: 2
  build&other:
    jobs:
      - build
      - other:
          requires:
            - build