version: 2
jobs:
  build:
    machine: true
    environment:
      GOSS_DST: /usr/local/bin
      GOSS_FILES_STRATEGY: cp
      GOSS_FILES_PATH: ~/project
    steps:
      - checkout
      - run: curl -fsSL https://goss.rocks/install | sudo sh
      - run: goss -version
      - run: docker build -t iynere/rust:test rust
      - run: dgoss run iynere/rust:test
