version: 2
jobs:
  
  build:
    machine: true
    steps:
      - checkout
      
      - run: docker info >/dev/null 2>&1 || service docker start
      
      - run:
          name: redis-server
          command: redis-server
          background: true
          
      - run:
          name: mongo
          command: mongodb
          background: true