version: 2
jobs:

  linux_job:
    machine: true
    steps:
      - checkout

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - scripts

  mac_job:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - attach_workspace:
          at: workspace

workflows:
  version: 2
  mac_and_linux:
    jobs:
      - linux_job
      - mac_job:
          requires:
            -  linux_job