version: 2.1

orbs:
  aws-cli-orb: iynere/aws-cli-orb@dev:master

jobs:
  test-aws-cli:
    executor: aws-cli-orb/default
    steps:
      - checkout

      - aws-cli-orb/install

      - aws-cli-orb/configure:
          profile-name: testing

workflows:
  version: 2
  test-orbs:
    jobs:
      - test-aws-cli:
          context: aws