version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile


steps-test: &steps-test
  run: |
    echo "hello"
    echo "another line"
    echo "line 3"
    echo "etc"


jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          background: true
          command: |
            circleci step halt
      - *steps-test
