version: 2
jobs:
  #### CHECKOUT JOB ####
  checkout_code:
    docker:
      # The first image listed here is the primary container image where all steps will run.
      - image: circleci/ruby:2.3.4-node-browsers
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  #### BUNDLE JOB ####
  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Restore bundle cache
      - restore_cache:
          keys:
            - avant-basic-bundle-cache-{{ checksum "Gemfile.lock" }}

      # Store bundle cache
      - save_cache:
          key: avant-basic-bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  #### PREPARE DATABASE JOB ####
  prepare_database:
    docker:
      # The first image listed here is the primary container image where all steps will run.
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          RAILS_ENV: test
      - image: circleci/postgres:9.6.6-alpine-postgis-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Restore bundle cache
      - restore_cache:
          keys:
            - avant-basic-bundle-cache-{{ checksum "Gemfile.lock" }}


      # Restore cache, if exists:
      - restore_cache:
          keys:
            - avant-basic-database-cache-{{ checksum "db_seeds_files_md5sums.txt" }}

      # Cache database dump and db configuration
      - save_cache:
          key: avant-basic-database-cache-{{ checksum "db_seeds_files_md5sums.txt" }}
          paths:
            - tmp/test_db_snapshot.dump
            - config/database.yml
  run_tests:
    parallelism: 5
    docker:
      # The first image listed here is the primary container image where all steps will run.
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          CIRCLE_TEST_REPORTS: test-reports
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          RAILS_ENV: test
          REDIS_URL: redis://localhost:6379
      - image: circleci/postgres:9.6.6-alpine-postgis-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
      - image: redis:3.2
    steps:
      #Restore source cache
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # Restore bundle cache
      - restore_cache:
          keys:
            - avant-basic-bundle-cache-{{ checksum "Gemfile.lock" }}
      #Restore database cache
      - restore_cache:
          keys:
            - avant-basic-database-cache-{{ checksum "db_seeds_files_md5sums.txt" }}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - prepare_database:
          requires:
            - bundle_dependencies
      - run_tests:
          requires:
            - prepare_database