experimental:
  notify:
    branches:
      only:
        - master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout

      - store_test_results:
          path: sandbox