version: 2
jobs:
  build:
    machine: true
    # docker:
    #   - image: circleci/ruby:2.5.1-stretch
    steps:
      - checkout

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            tags:
              only:  /.+/