version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - run: |
          git clone git@github.com:CircleCI-Public/circleci-dockerfiles.git
          touch foo
          touch bar
          cp -r . circleci-dockerfiles
          cd circleci-dockerfiles && ls