version: 2
jobs:
  jest-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: jest-results

  eslint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: eslint-results

  flow-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: flow-results

  stylelint-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: stylelint-results

  all-results:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: all-test-results

  all-results-no-flow:
    machine: true
    steps:
      - checkout
      - store_test_results:
          path: all-test-results-except-flow

  # all-results-no-eslint:
  #   machine: true
  #   steps:
  #     - checkout
  #     - store_test_results:
  #         path: all-test-results-except-eslint

workflows:
  version: 2
  test-results:
    jobs:
      - jest-results
      - eslint-results
      - flow-results
      - stylelint-results

      - all-results:
          requires:
            - jest-results
            - eslint-results
            - flow-results
            - stylelint-results

      - all-results-no-flow:
          requires:
            - jest-results
            - eslint-results
            - flow-results
            - stylelint-results

      # - all-results-no-eslint:
      #     requires:
      #       - jest-results
      #       - eslint-results
      #       - flow-results
      #       - stylelint-results