version: 2
jobs:
  build:
    docker:
      - image: iynere/code-dot-org:trusty-v2
    
    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce
        
      - run: docker-compose