version: 2
jobs:
  build:
    machine: true
    steps:

      - checkout

      - run: |
          echo "original CIRCLE_COMPARE_URL:" $CIRCLE_COMPARE_URL
          bash find_last_original_job_commit.sh