# 5.5.58-ram98 MB10 minutes ago

# 10.3.2-ram136 MB11 minutes ago

# 10.2.10-ram135 MB11 minutes ago

# 10.1.29-ram135 MB11 minutes ago

# 10.0.33-ram120 MB12 minutes ago

# 5.5.5898 MB15 minutes ago

# 10.3.2135 MB15 minutes ago

# 10.2.10135 MB15 minutes ago

# 10.1.29135 MB16 minutes ago

# 10.0.33

workflows:
  version: 2
  test_maria:
    jobs:
      - 5-5-58
      - 5-5-58-ram
      - 10-0-33
      - 10-0-33-ram
      - 10-1-29
      - 10-1-29-ram
      - 10-2-10
      - 10-2-10-ram
      - 10-3-2
      - 10-3-2-ram

version: 2
jobs:
  5-5-58:
    docker:
      - image: iynere/maria-test:5.5.58
    steps:
      - checkout
      
  5-5-58-ram:
    docker:
      - image: iynere/maria-test:5.5.58-ram
    steps:
      - checkout
       
  10-0-33:
    docker:
      - image: iynere/maria-test:10-0-33
    steps:
      - checkout
    
  10-0-33-ram:
    docker:
      - image: iynere/maria-test:10-0-33-ram
    steps:
      - checkout